apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: horizontalpodautoscalers.autoscaling.k8s.io
spec:
  group: autoscaling.k8s.io
  names:
    kind: HorizontalPodAutoscaler
    listKind: HorizontalPodAutoscalerList
    plural: horizontalpodautoscalers
    singular: horizontalpodautoscaler
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
              properties:
                name:
                  type: string
                namespace:
                  type: string
            spec:
              type: object
              properties:
                scaleTargetRef:
                  type: object
                  properties:
                    apiVersion:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
                minReplicas:
                  type: integer
                maxReplicas:
                  type: integer
                targetCPUUtilizationPercentage:
                  type: integer
            status:
              type: object
              properties:
                currentReplicas:
                  type: integer
                desiredReplicas:
                  type: integer
                currentCPUUtilizationPercentage:
                  type: integer

